"""Add received_amount field to track how much money has been gone through address

Revision ID: 39771ef66c0f
Revises: 1134da570f7d
Create Date: 2014-01-19 12:47:21.228812

"""

# revision identifiers, used by Alembic.
revision = '39771ef66c0f'
down_revision = '1134da570f7d'

from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sell_order', sa.Column('received_amount', sa.Numeric(), server_default='0.0', nullable=True))
    op.alter_column('sell_order', 'deposit_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sell_order', 'deposit_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('sell_order', 'received_amount')
    ### end Alembic commands ###
